apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: ecommerce
spec:
  selector:
    app: checkout
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: otel-lgtm/checkout:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability.svc.cluster.local:4318
            - name: CATALOG_URL
              value: http://catalog.ecommerce.svc.cluster.local:8080
            - name: INVENTORY_URL
              value: http://inventory.ecommerce.svc.cluster.local:8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
                - name: Host
                  value: checkout.ecommerce.svc.cluster.local
            initialDelaySeconds: 8
            periodSeconds: 5
